on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:2.4
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (Sofle Left)
        run: west build -s zmk/app -b bluemicro840_v1 -- -DSHIELD=ergotravel_left -DZMK_CONFIG="${GITHUB_WORKSPACE}"
      - name: Ergotravel DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/bluemicro840_v1.dts.pre.tmp
      - name: Ergotravel Left Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 ergotravel_left_bluemicro840_v1.uf2
      - name: Archive (ergotravel Left)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: sofle_left_bluemicro840_v1.uf2
      - name: West Build (ergotravel Right)
        run: west build --pristine -s zmk/app -b bluemicro840_v1 -- -DSHIELD=ergotravel_right -DZMK_CONFIG="${GITHUB_WORKSPACE}"

      - name: Ergotravel Right Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 ergotravel_right_bluemicro840_v1.uf2
      - name: Archive (Ergotravel Right)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: ergotravel_right_bluemicro840_v1.uf2
